# Data Acquisition
Loading each dataset into a pandas DataFrame and checking its shape.

In [1]:
import pandas as pd

## Primary 1: Fake news on Twitter, 2016 election (Grinberg et al. 2019)

In [2]:
twitter_daily = pd.read_csv("https://raw.githubusercontent.com/LazerLab/twitter-fake-news-replication/master/figure_1/data/daily_counts_exposures.csv")

print(twitter_daily.shape)
twitter_daily.head()

(128, 10)

,ts_rel_days,red,orange,black,N,date,pct_red,pct_orange,pct_black,pct_fake
0,-95,11071,7862,2608,407325,2016-08-05,0.027180,0.019302,0.006403,0.052884
1,-76,9478,8275,2386,419891,2016-08-24,0.022573,0.019707,0.005682,0.047962
2,2,13771,10922,2224,958011,2016-11-10,0.014375,0.011401,0.002321,0.028097
3,9,10661,9070,2961,616945,2016-11-17,0.017280,0.014701,0.004799,0.036781
4,1,11943,10562,1782,1262925,2016-11-09,0.009457,0.008363,0.001411,0.019231

In [3]:
twitter_daily.dtypes

ts_rel_days      int64
red              int64
orange           int64
black            int64
N                int64
date            object
pct_red        float64
pct_orange     float64
pct_black      float64
pct_fake       float64
dtype: object

In [4]:
print(twitter_daily["date"].min(), "to", twitter_daily["date"].max())

2016-08-01 to 2016-12-06

In [5]:
twitter_sites = pd.read_csv("https://raw.githubusercontent.com/LazerLab/twitter-fake-news-replication/master/coexposure_network/data/total_exposure_counts.csv")

print(twitter_sites.shape)
twitter_sites.sort_values("N", ascending=False).head(10)

(606, 2)

                website        N
21          nytimes.com  3404953
8               cnn.com  2301244
38   washingtonpost.com  2288172
23         politico.com  1805927
31          thehill.com  1784238
11   huffingtonpost.com  1527968
167       breitbart.com  1004415
58          foxnews.com  1001153
6               wsj.com   977073
64            slate.com   901170

## Primary 2: FakeNewsNet (PolitiFact articles)

In [6]:
fake = pd.read_csv("https://raw.githubusercontent.com/KaiDMML/FakeNewsNet/master/dataset/politifact_fake.csv")
real = pd.read_csv("https://raw.githubusercontent.com/KaiDMML/FakeNewsNet/master/dataset/politifact_real.csv")

fake["label"] = "fake"
real["label"] = "real"
news = pd.concat([fake, real])

print(news.shape)
news.head()

(1056, 5)

,id,news_url,title,tweet_ids,label
0,politifact15014,speedtalk.com/forum/viewtopic.php?t=51650,BREAKING: First NFL Team Declares Bankruptcy O...,937349434668498944\t937379378006282240\t937380...,fake
1,politifact15156,politics2020.info/index.php/2018/03/13/court-o...,Court Orders Obama To Pay $400 Million In Rest...,972666281441878016\t972678396575559680\t972827...,fake
2,politifact14745,www.nscdscamps.org/blog/category/parenting/467...,UPDATE: Second Roy Moore Accuser Works For Mic...,929405740732870656\t929439450400264192\t929439...,fake
3,politifact14355,https://howafrica.com/oscar-pistorius-attempts...,Oscar Pistorius Attempts To Commit Suicide,886941526458347521\t887011300278194176\t887023...,fake
4,politifact15371,http://washingtonsources.org/trump-votes-for-d...,Trump Votes For Death Penalty For Being Gay,915205698212040704\t915242076681506816\t915249...,fake

In [7]:
news.dtypes

id           object
news_url     object
title        object
tweet_ids    object
label        object
dtype: object

In [8]:
# tweet_ids is a list of tweet IDs separated by tabs, so counting them = number of tweets
news["num_tweets"] = news["tweet_ids"].str.split().str.len()

news.groupby("label")["num_tweets"].median()

label
fake    102.0
real     58.0
Name: num_tweets, dtype: float64

## Secondary 1: BuzzFeed Facebook fact-check (Sept 2016)

In [9]:
facebook = pd.read_csv("https://raw.githubusercontent.com/BuzzFeedNews/2016-10-facebook-fact-check/master/data/facebook-fact-check.csv")

print(facebook.shape)
facebook.head()

(2282, 12)

,account_id,post_id,Category,Page,Post URL,Date Published,Post Type,Rating,Debate,share_count,reaction_count,comment_count
0,184096565021911,1035057923259100,mainstream,ABC News Politics,https://www.facebook.com/ABCNewsPolitics/posts...,2016-09-19,video,no factual content,NaN,NaN,146.0,15.0
1,184096565021911,1035269309904628,mainstream,ABC News Politics,https://www.facebook.com/ABCNewsPolitics/posts...,2016-09-19,link,mostly true,NaN,1.0,33.0,34.0
2,184096565021911,1035305953234297,mainstream,ABC News Politics,https://www.facebook.com/ABCNewsPolitics/posts...,2016-09-19,link,mostly true,NaN,34.0,63.0,27.0
3,184096565021911,1035322636565962,mainstream,ABC News Politics,https://www.facebook.com/ABCNewsPolitics/posts...,2016-09-19,link,mostly true,NaN,35.0,170.0,86.0
4,184096565021911,1035352946562931,mainstream,ABC News Politics,https://www.facebook.com/ABCNewsPolitics/posts...,2016-09-19,video,mostly true,NaN,568.0,3188.0,2815.0

In [10]:
facebook.dtypes

account_id          int64
post_id             int64
Category           object
Page               object
Post URL           object
Date Published     object
Post Type          object
Rating             object
Debate             object
share_count       float64
reaction_count    float64
comment_count     float64
dtype: object

In [11]:
facebook["Rating"].value_counts()

Rating
mostly true                  1669
no factual content            264
mixture of true and false     245
mostly false                  104
Name: count, dtype: int64

## Secondary 2: News website quality ratings (Lin et al. 2023)

In [12]:
ratings = pd.read_csv("https://raw.githubusercontent.com/hauselin/domain-quality-ratings/main/data/domain_pc1.csv")

print(ratings.shape)
ratings.head()

(11520, 2)

                 domain       pc1
0           reuters.com  1.000000
1            apnews.com  0.998049
2  charitynavigator.org  0.985752
3          rollcall.com  0.982851
4    smithsonianmag.com  0.971184

In [13]:
# how many Twitter websites also have a quality rating? (checks that the join will work)
matches = twitter_sites["website"].isin(ratings["domain"]).sum()
print(matches, "out of", len(twitter_sites), "Twitter websites have a quality rating")

534 out of 606 Twitter websites have a quality rating